FROM kiawin/grpc-java-base

RUN mkdir generator
RUN mkdir generator/exe
RUN mkdir generator/lib
RUN mkdir generator/out

COPY exe/* /generator/exe/
COPY lib/* /generator/lib/
COPY out/* /generator/out/